### ISSUE TITLE
plugins not work

### ISSUE THREAD

**Issue by NuyyKatazou** [pablo67340/GUIShop#110]
Hello, i have this error : 

```
null
org.bukkit.command.CommandException: Unhandled exception executing command 'guishop' in plugin GUIShop v9.1.2
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[forge:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:157) ~[forge:?]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:767) ~[forge:7e29f765-296df566-9fb885e8]
at net.minecraft.network.play.ServerPlayNetHandler.func_147361_d(ServerPlayNetHandler.java:1819) ~[?:?]
at net.minecraft.network.play.ServerPlayNetHandler.func_147354_a(ServerPlayNetHandler.java:1666) ~[?:?]
at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(CChatMessagePacket.java:39) ~[?:?]
at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(CChatMessagePacket.java:10) ~[?:?]
at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$0(PacketThreadUtil.java:26) ~[?:?]
at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:153) ~[?:?]
at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:881) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:177) ~[?:?]
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:126) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:864) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:858) ~[?:?]
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:136) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:844) ~[?:?]
at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:764) ~[?:?]
at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:270) ~[?:?]
at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException: method can not be null
at java.util.Objects.requireNonNull(Objects.java:246) ~[?:?]
at com.github.stefvanschie.inventoryframework.shade.mininbt.ReflectionUtil.invokeMethod(ReflectionUtil.java:278) ~[?:?]
at com.github.stefvanschie.inventoryframework.shade.mininbt.NBTWrappers$NBTTagCompound.toNBT(NBTWrappers.java:399) ~[?:?]
at com.github.stefvanschie.inventoryframework.shade.mininbt.ItemNBTUtil.setNBTTag(ItemNBTUtil.java:55) ~[?:?]
at com.pablo67340.guishop.util.ItemUtil.setSell(ItemUtil.java:148) ~[?:?]
at com.pablo67340.guishop.commands.GuishopCommand.onCommand(GuishopCommand.java:113) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[forge:?]
... 20 more
```

**Comment by JuanJSAR** [comment]
I have the same error and I don't know how to solve it
