### ISSUE TITLE
GUIShop plugin wont load

### ISSUE THREAD

**Issue by Poopieheadyay** [pablo67340/GUIShop#116]
I help because I have no idea what is happening

[ERROR] Fatal error trying to convert GUIShop v9.1.5:com/pablo67340/guishop/GUIShop.class

java.lang.IllegalArgumentException: Unsupported class file major version 60

at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.<init>(ClassReader.java:196) ~[spigot-1.15.2.jar:git-Spigot-a99063f-8731c97]

at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.<init>(ClassReader.java:177) ~[spigot-1.15.2.jar:git-Spigot-a99063f-8731c97]

at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.<init>(ClassReader.java:163) ~[spigot-1.15.2.jar:git-Spigot-a99063f-8731c97]

at org.bukkit.craftbukkit.v1_15_R1.util.Commodore.convert(Commodore.java:128) ~[spigot-1.15.2.jar:git-Spigot-a99063f-8731c97]

at org.bukkit.craftbukkit.v1_15_R1.util.CraftMagicNumbers.processClass(CraftMagicNumbers.java:293) [spigot-1.15.2.jar:git-Spigot-a99063f-8731c97]

at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:140) [spigot-1.15.2.jar:git-Spigot-a99063f-8731c97]

at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) [spigot-1.15.2.jar:git-Spigot-a99063f-8731c97]

at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:953) [?:1.8.0_272]

at java.lang.ClassLoader.loadClass(ClassLoader.java:898) [?:1.8.0_272]

at java.lang.ClassLoader.loadClass(ClassLoader.java:881) [?:1.8.0_272]

at java.lang.Class.forNameImpl(Native Method) [?:1.8.0_272]

at java.lang.Class.forName(Class.java:408) [?:1.8.0_272]

at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) [spigot-1.15.2.jar:git-Spigot-a99063f-8731c97]

at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) [spigot-1.15.2.jar:git-Spigot-a99063f-8731c97]

at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) [spigot-1.15.2.jar:git-Spigot-a99063f-8731c97]

at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) [spigot-1.15.2.jar:git-Spigot-a99063f-8731c97]

at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:353) [spigot-1.15.2.jar:git-Spigot-a99063f-8731c97]

at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:210) [spigot-1.15.2.jar:git-Spigot-a99063f-8731c97]

at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [spigot-1.15.2.jar:git-Spigot-a99063f-8731c97]

at java.lang.Thread.run(Thread.java:823) [?:1.8.0_272]

[ERROR] Could not load 'plugins/GUIShop-9.1.5.jar' in folder 'plugins'

org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: JVMCFRE003 bad major version; class=com/pablo67340/guishop/GUIShop, offset=6

at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:139) ~[spigot-1.15.2.jar:git-Spigot-a99063f-8731c97]

at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[spigot-1.15.2.jar:git-Spigot-a99063f-8731c97]

at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) [spigot-1.15.2.jar:git-Spigot-a99063f-8731c97]

at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:353) [spigot-1.15.2.jar:git-Spigot-a99063f-8731c97]

at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:210) [spigot-1.15.2.jar:git-Spigot-a99063f-8731c97]

at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [spigot-1.15.2.jar:git-Spigot-a99063f-8731c97]

at java.lang.Thread.run(Thread.java:823) [?:1.8.0_272]

Caused by: java.lang.UnsupportedClassVersionError: JVMCFRE003 bad major version; class=com/pablo67340/guishop/GUIShop, offset=6

at java.lang.ClassLoader.defineClassImpl(Native Method) ~[?:1.8.0_272]

at java.lang.ClassLoader.defineClassInternal(ClassLoader.java:398) ~[?:1.8.0_272]

at java.lang.ClassLoader.defineClass(ClassLoader.java:359) ~[?:1.8.0_272]

at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_272]

at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163) ~[spigot-1.15.2.jar:git-Spigot-a99063f-8731c97]

at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[spigot-1.15.2.jar:git-Spigot-a99063f-8731c97]

at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:953) ~[?:1.8.0_272]

at java.lang.ClassLoader.loadClass(ClassLoader.java:898) ~[?:1.8.0_272]

at java.lang.ClassLoader.loadClass(ClassLoader.java:881) ~[?:1.8.0_272]

at java.lang.Class.forNameImpl(Native Method) ~[?:1.8.0_272]

at java.lang.Class.forName(Class.java:408) ~[?:1.8.0_272]

at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.15.2.jar:git-Spigot-a99063f-8731c97]

at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.15.2.jar:git-Spigot-a99063f-8731c97]

... 6 more

**Comment by pablo67340** [comment]
What Java version is your server using?
