### ISSUE TITLE
error when enabling GUIshop v9.1.9 (is it up to date?)

### ISSUE THREAD

**Issue by Tombo202020** [pablo67340/GUIShop#119]
[11:10:48] [Server thread/INFO]: [GUIShop] Enabling GUIShop v9.1.9
[11:10:48] [Server thread/ERROR]: Error occurred while enabling GUIShop v9.1.9 (Is it up to date?)
java.lang.NoClassDefFoundError: net/md_5/bungee/api/ChatColor
        at com.pablo67340.guishop.messages.Message.<init>(Message.java:30) ~[?:?]
        at com.pablo67340.guishop.messages.Message.<init>(Message.java:42) ~[?:?]
        at com.pablo67340.guishop.messages.MessageSystem.generateDefaults(MessageSystem.java:65) ~[?:?]
        at com.pablo67340.guishop.messages.MessageSystem.<init>(MessageSystem.java:33) ~[?:?]
        at com.pablo67340.guishop.GUIShop.onEnable(GUIShop.java:152) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[bukkit-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[bukkit-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[bukkit-1.18.2-R0.1-SNAPSHOT.jar:?]

**Comment by pablo67340** [comment]
Which server are you running this on? Spigot?
