### ISSUE TITLE
different java version

### ISSUE THREAD

**Issue by Hellscaped** [pablo67340/GUIShop#122]
[21:41:01] [Server thread/ERROR]: Could not load 'plugins/GUIShop-9.2.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: com/pablo67340/guishop/GUIShop has been compiled by a more recent version of the Java Runtime (class file vers>
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[patched.jar:git-TacoSpigot-"c80c1e5"]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:328) ~[patched.jar:git-TacoSpigot-"c80c1e5"]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [patched.jar:git-TacoSpigot-"c80c1e5"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:293) [patched.jar:git-TacoSpigot-"c80c1e5"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:203) [patched.jar:git-TacoSpigot-"c80c1e5"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-TacoSpigot-"c80c1e5"]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_345]
Caused by: java.lang.UnsupportedClassVersionError: com/pablo67340/guishop/GUIShop has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the >
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_345]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_345]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_345]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473) ~[?:1.8.0_345]
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_345]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_345]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_345]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_345]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_345]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched.jar:git-TacoSpigot-"c80c1e5"]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched.jar:git-TacoSpigot-"c80c1e5"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_345]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_345]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_345]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_345]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[patched.jar:git-TacoSpigot-"c80c1e5"]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[patched.jar:git-TacoSpigot-"c80c1e5"]
        ... 6 more

**Comment by pablo67340** [comment]
What version of Java is your server utilizing?

**Comment by Hellscap3d** [comment]
> What version of Java is your server utilizing?

java 11

**Comment by Hellscap3d** [comment]
openjdk

**Comment by pablo67340** [comment]
If you update your java to the latest (18 or 19) it should work fine

**Comment by Hellscap3d** [comment]
> If you update your java to the latest (18 or 19) it should work fine

I cannot do that easily
