### ISSUE TITLE
/shop command error

### ISSUE THREAD

**Issue by Samir-driod** [pablo67340/GUIShop#124]
When I run command /shop I have error

15:39:33 INFO]: [NBTAPI] [NBTAPI] Found Spigot: v1_20_R3! Trying to find NMS support
[15:39:33 WARN]: [NBTAPI] [NBTAPI] This Server-Version(v1_20_R3) is not supported by this NBT-API Version(2.9.2) located at com.pablo67340.guishop.shade.inventoryframework.shade.nbtapi.utils.MinecraftVersion. The NBT-API will try to work as good as it can! Some functions may not work!
[15:39:33 INFO]: [NBTAPI] [NBTAPI] Found Gson: class com.google.gson.Gson
[15:39:33 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'shop' in com.pablo67340.guishop.commands.BuyCommand(shop)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:999) ~[paper-1.20.4.jar:git-Paper-454]
	at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.4.jar:git-Paper-454]
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:32) ~[paper-1.20.4.jar:git-Paper-454]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.20.4.jar:git-Paper-454]
	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.20.4.jar:git-Paper-454]
	at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[paper-1.20.4.jar:git-Paper-454]
	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:101) ~[paper-1.20.4.jar:git-Paper-454]
	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:434) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:336) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:323) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2230) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2190) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-454]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1465) ~[paper-1.20.4.jar:git-Paper-454]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-454]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1442) ~[paper-1.20.4.jar:git-Paper-454]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1365) ~[paper-1.20.4.jar:git-Paper-454]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1343) ~[paper-1.20.4.jar:git-Paper-454]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1232) ~[paper-1.20.4.jar:git-Paper-454]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-454]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: com.pablo67340.guishop.shade.inventoryframework.shade.nbtapi.NbtApiException: [?]Error while calling the method 'putString(java.lang.String,java.lang.String)', loaded: true, Enum: COMPOUND_SET_STRING Passed Class: class java.lang.Boolean
	at com.pablo67340.guishop.shade.inventoryframework.shade.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:180) ~[GUIShop-9.1.7.jar:?]
	at com.pablo67340.guishop.shade.inventoryframework.shade.nbtapi.NBTReflectionUtil.setData(NBTReflectionUtil.java:611) ~[GUIShop-9.1.7.jar:?]
	at com.pablo67340.guishop.shade.inventoryframework.shade.nbtapi.NBTCompound.setString(NBTCompound.java:101) ~[GUIShop-9.1.7.jar:?]
	at com.pablo67340.guishop.shade.inventoryframework.GuiItem.<init>(GuiItem.java:61) ~[GUIShop-9.1.7.jar:?]
	at com.pablo67340.guishop.shade.inventoryframework.GuiItem.<init>(GuiItem.java:72) ~[GUIShop-9.1.7.jar:?]
	at com.pablo67340.guishop.listenable.Menu.loadMenu(Menu.java:127) ~[GUIShop-9.1.7.jar:?]
	at com.pablo67340.guishop.listenable.Menu.loadItems(Menu.java:99) ~[GUIShop-9.1.7.jar:?]
	at com.pablo67340.guishop.listenable.Menu.open(Menu.java:195) ~[GUIShop-9.1.7.jar:?]
	at com.pablo67340.guishop.listenable.PlayerListener.openMenu(PlayerListener.java:73) ~[GUIShop-9.1.7.jar:?]
	at com.pablo67340.guishop.commands.UserCommand.buyCommand(UserCommand.java:62) ~[GUIShop-9.1.7.jar:?]
	at com.pablo67340.guishop.commands.BuyCommand.execute(BuyCommand.java:39) ~[GUIShop-9.1.7.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	... 28 more
Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@14c2b7dd
	at jdk.internal.reflect.GeneratedMethodAccessor19.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at com.pablo67340.guishop.shade.inventoryframework.shade.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:178) ~[GUIShop-9.1.7.jar:?]
	at com.pablo67340.guishop.shade.inventoryframework.shade.nbtapi.NBTReflectionUtil.setData(NBTReflectionUtil.java:611) ~[GUIShop-9.1.7.jar:?]
	at com.pablo67340.guishop.shade.inventoryframework.shade.nbtapi.NBTCompound.setString(NBTCompound.java:101) ~[GUIShop-9.1.7.jar:?]
	at com.pablo67340.guishop.shade.inventoryframework.GuiItem.<init>(GuiItem.java:61) ~[GUIShop-9.1.7.jar:?]
	at com.pablo67340.guishop.shade.inventoryframework.GuiItem.<init>(GuiItem.java:72) ~[GUIShop-9.1.7.jar:?]
	at com.pablo67340.guishop.listenable.Menu.loadMenu(Menu.java:127) ~[GUIShop-9.1.7.jar:?]
	at com.pablo67340.guishop.listenable.Menu.loadItems(Menu.java:99) ~[GUIShop-9.1.7.jar:?]
	at com.pablo67340.guishop.listenable.Menu.open(Menu.java:195) ~[GUIShop-9.1.7.jar:?]
	at com.pablo67340.guishop.listenable.PlayerListener.openMenu(PlayerListener.java:73) ~[GUIShop-9.1.7.jar:?]
	at com.pablo67340.guishop.commands.UserCommand.buyCommand(UserCommand.java:62) ~[GUIShop-9.1.7.jar:?]
	at com.pablo67340.guishop.commands.BuyCommand.execute(BuyCommand.java:39) ~[GUIShop-9.1.7.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	... 28 more
[15:39:33 WARN]: [NBTAPI] [NBTAPI] The NBT-API located at 'package com.pablo67340.guishop.shade.inventoryframework.shade.nbtapi' seems to be outdated!
[15:39:33 WARN]: [NBTAPI] [NBTAPI] Current Version: '2.9.2' Newest Version: 2.12.2'
[15:39:33 WARN]: [NBTAPI] [NBTAPI] Please update the NBTAPI or the plugin that contains the api(nag the mod author when the newest release has an old version, not the NBTAPI dev)!

I have installed NBT-API plugin (version 2.12.2 but it uses 2.9.2). I have downloaded it from spigot page but still the same.
My java version is:
openjdk 17.0.10 2024-01-16
OpenJDK Runtime Environment (build 17.0.10+7-Ubuntu-122.04.1)
OpenJDK 64-Bit Server VM (build 17.0.10+7-Ubuntu-122.04.1, mixed mode, sharing)

All plugins are up to date.

**Comment by pablo67340** [comment]
Just added 1.20x support
