### ISSUE TITLE
All comands break after reloading plugin with build in commands. Only way to fix is to restart the server.

### ISSUE THREAD

**Issue by SimplyJeevS** [pablo67340/GUIShop#128]
This makes it borderline impossible to edit the config and configure prices properly. Paper 1.21.1, using latest jar
I tried to get into contact on discord but the link has been expired, Left a review on spigot.

[22:32:01 INFO]: [NBTAPI] [NBTAPI] Found Minecraft: 1.21.1! Trying to find NMS support
[22:32:01 WARN]: [NBTAPI] [NBTAPI] This Server-Version(1.21.1-R0.1-SNAPSHOT) is not supported by this NBT-API Version(2.13.1) located in GUIShop. The NBT-API will try to work as good as it can! Some functions may not work!
[22:32:01 INFO]: [NBTAPI] [NBTAPI] Using the plugin 'GUIShop' to create a bStats instance!
[22:32:01 WARN]: [NBTAPI] #########################################- NBTAPI -#########################################
[22:32:01 WARN]: [NBTAPI] The NBT-API inside GUIShop is the plugin version, not the API!
[22:32:01 WARN]: [NBTAPI] The plugin itself should never be shaded! Remove the `-plugin` from the dependency and fix your shading setup.
[22:32:01 WARN]: [NBTAPI] For more info check: https://github.com/tr7zw/Item-NBT-API/wiki/Using-Maven#option-2-shading-the-nbt-api-into-your-plugin
[22:32:01 WARN]: [NBTAPI] #########################################- NBTAPI -#########################################
[22:32:01 ERROR]: Command exception: /guishop sell 0.5
org.bukkit.command.CommandException: Unhandled exception executing command 'guishop' in plugin GUIShop v9.2.3
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.3.10.jar:?]
at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:443) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
at net.minecraft.commands.Commands.performCommand(Commands.java:350) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
at net.minecraft.commands.Commands.performCommand(Commands.java:332) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2218) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2192) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1466) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1473) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1318) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError
at GUIShop-9.2.3.jar/com.pablo67340.guishop.shade.nbtapi.nbtapi.NBTCompound.setDouble(NBTCompound.java:242) ~[GUIShop-9.2.3.jar:?]
at GUIShop-9.2.3.jar/com.pablo67340.guishop.util.ItemUtil.setSellPrice(ItemUtil.java:132) ~[GUIShop-9.2.3.jar:?]
at GUIShop-9.2.3.jar/com.pablo67340.guishop.commands.GuishopCommand.onCommand(GuishopCommand.java:186) ~[GUIShop-9.2.3.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
... 27 more
Caused by: java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "pk" is null
at java.base/java.util.ImmutableCollections$MapN.probe(ImmutableCollections.java:1328) ~[?:?]
at java.base/java.util.ImmutableCollections$MapN.get(ImmutableCollections.java:1242) ~[?:?]
at java.base/java.util.ImmutableCollections$AbstractImmutableMap.getOrDefault(ImmutableCollections.java:1097) ~[?:?]
at io.papermc.paper.pluginremap.reflect.PaperReflection.mapDeclaredFieldName(PaperReflection.java:79) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.getDeclaredField(AbstractDefaultRulesReflectionProxy.java:90) ~[reflection-rewriter-runtime-0.0.3.jar:?]
at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.getDeclaredField(Unknown Source) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
at GUIShop-9.2.3.jar/com.pablo67340.guishop.shade.nbtapi.nbtapi.NBTReflectionUtil.<clinit>(NBTReflectionUtil.java:59) ~[GUIShop-9.2.3.jar:?]
at GUIShop-9.2.3.jar/com.pablo67340.guishop.shade.nbtapi.nbtapi.NBTCompound.setDouble(NBTCompound.java:242) ~[GUIShop-9.2.3.jar:?]
at GUIShop-9.2.3.jar/com.pablo67340.guishop.util.ItemUtil.setSellPrice(ItemUtil.java:132) ~[GUIShop-9.2.3.jar:?]
at GUIShop-9.2.3.jar/com.pablo67340.guishop.commands.GuishopCommand.onCommand(GuishopCommand.java:186) ~[GUIShop-9.2.3.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
... 27 more
[22:32:03 INFO]: jefkeXD issued server command: /sell
[22:32:07 INFO]: jefkeXD issued server command: /guishop sell 5

**Comment by pablo67340** [comment]
Looks like ItemNBT API had issues with paper 1.21, and not GUIShop. 

https://github.com/tr7zw/Item-NBT-API/releases

If you look at the most recent releases, you can see it's fixed. I will see to updating GUIShop if these authors have updated as well.
