### ISSUE TITLE
Update causes plugin not to load

### ISSUE THREAD

**Issue by xxroltsxx** [pablo67340/GUIShop#4]
Hello, I just got the latest version of this plugin from dev.bukkit but am unable to load the plugin.

Here is the error I am getting:
`2015-10-08 11:35:55 | [ERROR] Could not load 'plugins/GUIShop (1).jar' in folder 'plugins'
2015-10-08 11:35:55 | [RAW] org.bukkit.plugin.InvalidPluginException: java.lang.Error: Unresolved compilation problem:
2015-10-08 11:35:55 | [RAW]     The type com.avaje.ebean.EbeanServer cannot be resolved. It is indirectly referenced from required .class files
2015-10-08 11:35:55 | [RAW]
2015-10-08 11:35:55 | [RAW]     at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
2015-10-08 11:35:55 | [RAW]     at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
2015-10-08 11:35:55 | [RAW]     at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
2015-10-08 11:35:55 | [RAW]     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
2015-10-08 11:35:55 | [RAW]     at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
2015-10-08 11:35:55 | [RAW]     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
2015-10-08 11:35:55 | [RAW]     at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
2015-10-08 11:35:55 | [RAW] Caused by: java.lang.Error: Unresolved compilation problem:
2015-10-08 11:35:55 | [RAW]     The type com.avaje.ebean.EbeanServer cannot be resolved. It is indirectly referenced from required .class files
2015-10-08 11:35:55 | [RAW]
2015-10-08 11:35:55 | [RAW]     at com.pablo67340.GUIShop.Main.Main.<init>(Main.java:1) ~[?:?]
2015-10-08 11:35:55 | [RAW]     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_60]
2015-10-08 11:35:55 | [RAW]     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_60]
2015-10-08 11:35:55 | [RAW]     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_60]
2015-10-08 11:35:55 | [RAW]     at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_60]
2015-10-08 11:35:55 | [RAW]     at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_60]
2015-10-08 11:35:55 | [RAW]     at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
2015-10-08 11:35:55 | [RAW]     at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
2015-10-08 11:35:55 | [RAW]     ... 6 more`

**Comment by pablo67340** [comment]
It has been fixed!
