### ISSUE TITLE
Bugs and Suggestion

### ISSUE THREAD

**Issue by NoHoPeLess** [pablo67340/GUIShop#6]
Hello, as i posted on Spigot, now i try it here:

We use:
- Spigot 1.10
- GUI Shop 4.5
- Craftconommy 3.3
- Vault 1.5.6

-Sell dont work! I try something but nothing happens... when i do /sell and put items in there, nothing happens and when the menu is close, the items are all disapear (no exceptions in the console/log)

-The /shop works but 2 options dont work:
i cant buy for example 1 stone (shift+click) when i do the shop is closed
i cant sell items (yes is has the same  quantity but it dont work
(no exceptions in the console/log)

-When i try to sell an item with custom lore it happens into an exception:
`[08:11:34] [Server thread/ERROR]: Could not pass event InventoryClickEvent to GUIShop v4.5
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[custom.jar:git-Spigot-c55900f-9856d8a]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[custom.jar:git-Spigot-c55900f-9856d8a]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [custom.jar:git-Spigot-c55900f-9856d8a]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [custom.jar:git-Spigot-c55900f-9856d8a]
    at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1853) [custom.jar:git-Spigot-c55900f-9856d8a]
    at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:33) [custom.jar:git-Spigot-c55900f-9856d8a]
    at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:10) [custom.jar:git-Spigot-c55900f-9856d8a]
    at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [custom.jar:git-Spigot-c55900f-9856d8a]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_73]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_73]
    at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [custom.jar:git-Spigot-c55900f-9856d8a]
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:733) [custom.jar:git-Spigot-c55900f-9856d8a]
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [custom.jar:git-Spigot-c55900f-9856d8a]
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [custom.jar:git-Spigot-c55900f-9856d8a]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [custom.jar:git-Spigot-c55900f-9856d8a]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
Caused by: java.lang.NumberFormatException: For input string: "Frisch aus der niggy Konditorei]"
    at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:1.8.0_73]
    at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_73]
    at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_73]
    at com.pablo67340.GUIShop.Listeners.PlayerListener.onShopClick(PlayerListener.java:299) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor43.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[custom.jar:git-Spigot-c55900f-9856d8a]
    ... 15 more`

If it helps you (start log include shop and sell open): http://pastebin.com/keC3CP6Y

Config file: http://pastebin.com/qyPZNjPK

Shop file: is standard

atm 1 suggestion, can we please remove the $ in front of each price/sells? Can we make custom one?

For now nice Plugin but with this bugs, the pl is unuseable. Please fix this :) so i can rate you on spigot

**Comment by pablo67340** [comment]
I will be looking into these fixes shortly, I am debating on re-writing most of the listener method itself.

**Comment by LavaIngot** [comment]
I am also experiencing the same error, only this happens when I try to open a shop, and also I have 7 shops configured, but the GUI only shows 4
