### ISSUE TITLE
PlayerCommandPreprocessEvent on v4.6

### ISSUE THREAD

**Issue by jeremy100** [pablo67340/GUIShop#7]
GuiShop version: 4.6
Server version: 1.10 (normal Spigot)
Other plugins: Essentials, Vault 1.5.6
Plugin config & shop: default
Error on open the shop
----------------------------------------------------------------
[18:06:46 INFO]: Terachnos issued server command: /shop
[18:06:46 ERROR]: Could not pass event PlayerCommandPreprocessEvent to GUIShop v4.6
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.10.2.jar:git-Spigot-af8198d-8cc5958]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10.2.jar:git-Spigot-af8198d-8cc5958]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.2.jar:git-Spigot-af8198d-8cc5958]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.2.jar:git-Spigot-af8198d-8cc5958]
        at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1343) [spigot-1.10.2.jar:git-Spigot-af8198d-8cc5958]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186) [spigot-1.10.2.jar:git-Spigot-af8198d-8cc5958]
        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.10.2.jar:git-Spigot-af8198d-8cc5958]
        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.10.2.jar:git-Spigot-af8198d-8cc5958]
        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.2.jar:git-Spigot-af8198d-8cc5958]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_101]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_101]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.2.jar:git-Spigot-af8198d-8cc5958]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot-1.10.2.jar:git-Spigot-af8198d-8cc5958]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2.jar:git-Spigot-af8198d-8cc5958]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2.jar:git-Spigot-af8198d-8cc5958]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-af8198d-8cc5958]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_10_R1.entity.CraftHumanEntity.openInventory(CraftHumanEntity.java:183) ~[spigot-1.10.2.jar:git-Spigot-af8198d-8cc5958]
        at com.pablo67340.GUIShop.Handlers.Menu.openMenu(Menu.java:110) ~[?:?]
        at com.pablo67340.GUIShop.Listeners.PlayerListener.onCommand(PlayerListener.java:77) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.10.2.jar:git-Spigot-af8198d-8cc5958]
        ... 16 more
>

**Comment by pablo67340** [comment]
You have an error in your config.yml
