### ISSUE TITLE
Cannot Run /shop, unhandled exception

### ISSUE THREAD

**Issue by UltraBlackLinux** [pablo67340/GUIShop#70]
So everytime Im running /shop Im getting this error:
[21:45:52 ERROR]: null
 org.bukkit.command.CommandException: Unhandled exception executing 'shop' in com.pablo67340.guishop.commands.BuyCommand(shop)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:147) ~[SimpleCommandMap.class:44e91f6]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:688) ~[CraftServer.class:44e91f6]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1615) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1450) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:50) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:11) [la.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_252]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:924) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:456) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:861) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:733) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.lang.NullPointerException: method can not be null
        at java.util.Objects.requireNonNull(Objects.java:228) ~[?:1.8.0_252]
        at com.github.stefvanschie.inventoryframework.shade.mininbt.ReflectionUtil.invokeMethod(ReflectionUtil.java:278) ~[?:?]
        at com.github.stefvanschie.inventoryframework.shade.mininbt.NBTWrappers$NBTTagCompound.toNBT(NBTWrappers.java:399) ~[?:?]
        at com.github.stefvanschie.inventoryframework.shade.mininbt.ItemNBTUtil.setNBTTag(ItemNBTUtil.java:55) ~[?:?]
        at com.github.stefvanschie.inventoryframework.GuiItem.<init>(GuiItem.java:61) ~[?:?]
        at com.github.stefvanschie.inventoryframework.GuiItem.<init>(GuiItem.java:70) ~[?:?]
        at com.pablo67340.guishop.listenable.Menu.buildMenuItem(Menu.java:84) ~[?:?]
        at com.pablo67340.guishop.listenable.Menu.preLoad(Menu.java:67) ~[?:?]
        at com.pablo67340.guishop.listenable.Menu.open(Menu.java:104) ~[?:?]
        at com.pablo67340.guishop.listenable.PlayerListener.openShop(PlayerListener.java:46) ~[?:?]
        at com.pablo67340.guishop.commands.GuishopUserCommand.buyCommand(GuishopUserCommand.java:52) ~[?:?]
        at com.pablo67340.guishop.commands.BuyCommand.execute(BuyCommand.java:23) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[SimpleCommandMap.class:44e91f6]
        ... 14 more

What does this mean? How do I solve this?
Thanks!

**Comment by UltraBlackLinux** [comment]
Fixed in PR #43

**Comment by UltraBlackLinux** [comment]
ok nvm - plugin.yml thing

**Comment by UltraBlackLinux** [comment]
Im using the newest version (8.0) I thought there was a pull request?
