### ISSUE TITLE
server command:  /shop

### ISSUE THREAD

**Issue by SpiderAang** [pablo67340/GUIShop#84]
> [14:00:28] [Server thread/INFO]: SpiderAang issued server command: /store
> [14:00:28] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'store' in com.pablo67340.guishop.commands.BuyCommand(shop)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:156) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:758) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:1788) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1631) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1584) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:941) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:934) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:918) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:850) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.ClassCastException: com.pablo67340.guishop.commands.GuishopUserCommand cannot be cast to com.pablo67340.guishop.commands.GuishopUserCommand
at com.pablo67340.guishop.Main.getUserCommands(Main.java:235) ~[?:?]
at com.pablo67340.guishop.commands.BuyCommand.execute(BuyCommand.java:23) ~[?:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
... 18 more

**Comment by Skyslycer** [comment]
Basicly restart the server and NEVER do a reload. Reloads dont just break this plugin, but do many othera too like LibsDisguises or sum. I completely switched to /stop and and then started the server again. 
I hope that helps.

**Comment by Skyslycer** [comment]
If that fixed it please close the issue, because we would like to keep the issue section clean.

**Comment by pablo67340** [comment]
Issue Closed. /gs reload is the expected reloading measure.
