### ISSUE TITLE
/sell not functioning on 1.16.4 (with essentials)

### ISSUE THREAD

**Issue by AnimeDasher** [pablo67340/GUIShop#91]
Two problems im having:
1. Essentials /sell conflicts with this one
2. /guishop sell 10   is refusing to work giving me this error:
[13:34:15 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'guishop' in plugin GUIShop v8.4
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.4.jar:git-Paper-416]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.4.jar:git-Paper-416]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:807) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2021) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1832) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1785) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1132) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1125) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1086) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-416]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.NullPointerException
	at com.pablo67340.guishop.util.ItemUtil.setSell(ItemUtil.java:103) ~[?:?]
	at com.pablo67340.guishop.commands.GuishopCommand.onCommand(GuishopCommand.java:119) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.4.jar:git-Paper-416]
	... 19 more
``

**Comment by Skyslycer** [comment]
1. problem easy fix: there is a way to like parse commands to other plugins. lemme look this up.
https://www.spigotmc.org/threads/essentialsx-overriding-other-plugins-commands.268951/
2. problem: i dont really know whats going on there, but next time just remove the "10" and it should work. 
If it doesnt, just answer to this comment and ill investigate in the code.

**Comment by AnimeDasher** [comment]
says for me to specify a value when i run guishop sell with the alias /gsell

**Comment by Skyslycer** [comment]
then set the sell command to sum like playersell just for testing.
if that works u can look what aliases arent used yet and use them

**Comment by AnimeDasher** [comment]
> then set the sell command to sum like playersell just for testing.
> if that works u can look what aliases arent used yet and use them

so guishop playersell?

**Comment by AnimeDasher** [comment]
could you please test on 1.16.4 to see if i have something misconfigured?

**Comment by pablo67340** [comment]
1. In your config.yml, you can rename the GUIShop sell command to anything of your choice. If /sell doesn't work for you, you can change it to something else. The odd part is, I am using Essentials currently on 1.16.5, and /sell doesn't mess with Essentials at all.


2. 
/guishop sell 10 is not how the command is intended to be used.

Depending on your config.yml, you set custom sell commands to open the sell GUI. Default is /sell.

All a user would type is /sell, which opens a blank chest. You drop the items inside and close it. This will attempt to sell the items in the GUI.

**Comment by Skyslycer** [comment]
It works for me on 1.16.5 and 1.16.4 completely fine
